generate_config() {
  local pkgs=($(pacman -Qqent))
  echo "# Generated by Architect on $(date)"
  echo "# Feel free to edit. Detected packages are in the [detected] set."
  echo
  echo "declare -A packages_by_set=("
  echo "  [detected]=\"$(printf '%s\n' "${pkgs[@]}")\""
  echo ")"
  echo
  echo "system_packages=(detected)"
  echo "aur_packages=()"
  echo "declare -A aur_packages_by_set=()"
  echo "declare -A expected_versions_config=()"
  echo "declare -A dotfiles=()"
  echo "post_install() { echo; } # no-op"
  echo "pre_remove() { echo; } # no-op"
  exit
}

help() {
  cat <<EOF
Architect - Declarative system manager for Arch GNU/Linux systems

Usage:
  $0 [options]

Options:
  --make-config             Generate a template config and prints it in stdout
  --validate                Validate the config file at \$ARCHITECT_CONFIG
  --dry-run                 Simulate all operations without making changes
  --force                   Forces stuff without confirmation
  --take-snapshot-now       Save current package list as a snapshot
  --rollback                Revert to the latest snapshot
  --diff                    Show package differences from current config
  --apply-diff              Install/remove packages to match config
  --no-snapshot             Skip creating automatic snapshot
  --list-snapshots          List saved snapshots
  --purge-all-snapshots     Purge all saved snapshots (USE WITH CAUTION)
  --purge-snapshots <last>  Purge all saved snapshots and keep last <last> (default: 3)
  --install-aur-only        Build and install only AUR packages
  --pacstrap <dir>          Bootstrap a new Arch system at <dir> using config
  --dotfiles-sync|edit|status
                           Manage dotfiles defined in config
  --help                    Show this help message
  --version                 Show Architect version

Environment:
  ARCHITECT_CONFIG          Path to config file (default: /etc/architect.sh)
  ARCHITECT_DIR             Base dir for snapshots, dotfiles, etc (default: ~/.architect)

Examples:
  $0 --dry-run
  ARCHITECT_CONFIG=./myconfig.sh $0 --install-aur-only
  $0 --pacstrap /mnt

EOF
  exit
}

version() {
  echo "Architect v$VERSION"
  exit
}
